### ISSUE TITLE
Simplify licensing

### ISSUE THREAD

**Issue by BigBlueHat** [timothee-haudebourg/json-ld#1]
First, thanks for implementing JSON-LD in Rust! 😁 

It's a bit confusing to license the code under *either* the Apache License 2.0 (which comes with naming protections, and some patent stuff) and the MIT (which lacks those).

There is some (evergreen...) debate around Apache 2.0's compatibility with the GPLv2 license family, but otherwise it's broadly compatible. The MIT is guaranteed to be legally compatible with nearly everything--because it has so few limitations.

Would you be open to use using *only* the MIT (or Apache-2.0)?

It would simplify things for other developers and yourself (should you ever need to enforce the license).

Thanks for considering this, and thanks for building this project!
🎩

**Comment by timothee-haudebourg** [comment]
Hi, thanks for your interest in this project :)

I would prefer licensing under the Apache License 2.0 which provides explicit protections against patent trolling. However it is not compatible with the GPLv2, which may be an issue in the future. The MIT license, while dropping these protections, is compatible with the GPLv2.

I you have no problems with either of those licenses, I am not sure to see why the double licensing would be an issue here. If it is confusing for you, you may only consider the Apache License 2.0 and forget about the MIT, which will probably only be used by GPLv2 softwares.

Note that, this early in the project (although I may publish the crate any time now), I *am* open for this kind of discussions. However I am not quite convinced by the "it's confusing" argument, since choosing one license does not bind you to the other.

Feel free to insist if you think this can lead to other problems that I'm overseeing.

**Comment by BigBlueHat** [comment]
I figured GPLv2 compatibility was the aim. Unfortunate mess, that... 😕 

Given that anyone can choose either license, I'm not sure the Apache License 2.0 technically offers anything over the MIT. Anyone wanting to avoid the protection against patent trolling would likely be avoidable by their saying they'd used it under the MIT--side stepping the protections.

At any rate, the "CLA" style text you have in the README should be sufficient to help contributors understand they're contributing under both the MIT & Apache-2.0 which does give you (and others) the freedom to use either.

However, just using the MIT would be "cleaner" but I can understand still wanting the protections of the Apache-2.0...if you can still make them apply when it counts.

Thanks for entertaining this discussion! OSS licensing is a space I work in, so I'm fascinated by the various choices people and projects make to deal with the "tangle" that is licensing terms. 😃 

Regardless of any of the licensing stuff, I'm excited you've built this, and I look forward to promoting it to Rust dev friends and JSON-LD folks.

Cheers!
🎩
