### ISSUE TITLE
Option to not drop unmapped properties

### ISSUE THREAD

**Issue by clehner** [timothee-haudebourg/json-ld#13]
W3C CCG's [VC HTTP API Test Suite](https://github.com/w3c-ccg/vc-http-api-test-suite) requires that [Verifiable Credentials](https://www.w3.org/TR/vc-data-model/) with certain JSON-LD-based [Linked Data Proofs](https://w3c-ccg.github.io/ld-proofs/) do not discard certain properties when expanding a JSON-LD document, as in the following two tests:
- "4. The Verifier\'s Verify Credential HTTP API MUST fail to verify a Verifiable Credential with a property added to the credential." https://github.com/w3c-ccg/vc-http-api-test-suite/blob/61d498cd04c45a22b9578774e6a066b59a8f4e94/packages/vc-http-api-test-server/__tests__/verifyCredential.spec.js#L80
- "7. The Verifier's Verify Credential HTTP API MUST fail to verify a Verifiable Credential with a property added to the proof." https://github.com/w3c-ccg/vc-http-api-test-suite/blob/61d498cd04c45a22b9578774e6a066b59a8f4e94/packages/vc-http-api-test-server/__tests__/verifyCredential.spec.js#L114-L122

These two tests involve inserting a property-value `"newProp": "bar"` - in the verifiable credential object, or in the proof object, respectively. Both of those objects are JSON-LD documents. Neither `newProp` or `bar` are defined in the JSON-LD context for these objects.

I see two possible ways to accomplish the negative test result:
1. Throw an error.
2. Expand the value to something, such that the document's RDF deserialization canonicalization results in a different value, so that the signature verification fails.

Before 7c9fd8e1340e26535f8988068736ca4b6fb5101c, the strict expansion mode added in https://github.com/timothee-haudebourg/json-ld/pull/4 could be used to accomplish 1. Currently the strict option is discarded.

I thought that 2 might be possible if the expansion base IRI option was passed, so that the property would get normalized as a relative IRI reference from the base IRI, but I didn't find that to work. I think I have seen JSON-LD Playground do that sometimes, but I'm unable to reproduce that now. Maybe this only happens when `@vocab` is in effect?

Some RDF deserialization tests require, however, that unexpandable properties are in fact dropped. FWIW, these are: tc014, tc018, te003, te016, te032, te059, te060, tin06, tpr06, tpr19, tpr36, tpr38, twf02 - which fail in `ssi` if the boolean for lax/strict mode is changed on this line: https://github.com/spruceid/ssi/blob/3e77c9b/src/jsonld.rs#L1630.

With the previous behavior of the strict expansion mode binary option, `ssi` could let the properties be silently dropped for RDF Deserialization Test Suite, while instead throwing a key expansion error for VC HTTP API. I think that allowing the unmapped properties expand to *some* IRI would also address both of these test requirements - but I don't know if there is a valid way to do that... [except maybe to use `@vocab` in an `expandContext` with a randomly generated URL and then error if that URL appears in the output.]

`jsonld.js` handles this issue using an `expansionMap` option - that seems to be like a functional generalization of the strict mode idea:
- https://github.com/digitalbazaar/jsonld.js/blob/20e2286/lib/expand.js#L75
- https://github.com/digitalbazaar/jsonld.js/blob/20e2286/lib/expand.js#L61-L65

`jsonld-signatures` (used by [vc-js](https://github.com/digitalbazaar/vc-js)) passes a function for `jsonld.js`'s `expansionMap` option that throws an error, saying `The property "..." in the input was not defined in the context`:
https://github.com/digitalbazaar/jsonld-signatures/blob/9a665c5/lib/expansionMap.js

Would there be any suggested way to accomplish this behavior (an option or technique to continue to expand instead of dropping properties), or could the previous behavior of the strict mode be re-added?

**Comment by timothee-haudebourg** [comment]
Terms that are not defined in the context are dropped unless:
- there is a vocabulary binding defined in the context, in which case it is expanded into the concatenation vocabulary + term; or
- there is a `:` character in the term (that may be what you have seen in the playground?). If the term is not an IRI nor a blank node identifier, it will be inserted in the expanded document as a `Reference::Invalid` variant. This is new to version 0.3.0, which is why the `strict` option disappeared (although I forgot to completely remove it, it is currently useless).

If I understand well, you want to avoid silent dropping of terms by either (1) raising an error when one is dropped (2) not dropping them at all. What I can propose is to introduce some kind of "expansion policies" defined in the expansion options:
- "normal": the current policy, where terms are silently dropped;
- "strict": terms that cannot be expanded and do not contain a `:` character will raise an error;
- "stricter": terms that cannot be expanded into an IRI nor a blank node identifier (whether or not they contain a `:` character) will raise an error (no instances of `Reference::Invalid` are created);
- "relaxed": terms that cannot be expanded are preserved, even if they have no `:` character, and made into a `Reference::Invalid`.

For now I don't have a way to send back warnings generated during expansion, but generating a warning when a term is dropped could also be a solution later.

**Comment by timothee-haudebourg** [comment]
I've released #14 in the new version 0.4.0.
