### ISSUE TITLE
Is there a way to convert an ExpandedDocument to a JSON Value

### ISSUE THREAD

**Issue by pchampin** [timothee-haudebourg/json-ld#47]
My [current implementation](https://github.com/pchampin/sophia_rs/tree/main/jsonld) implements `toRdf` from a [`json::JsonValue`](https://docs.rs/json/latest/json/enum.JsonValue.html). The easiest way for me to port it to use this crate would be to convert an [`ExpandedDocument`](https://docs.rs/json-ld/latest/json_ld/struct.ExpandedDocument.html) into a [`json-syntax::Value`](https://docs.rs/json-syntax/latest/json_syntax/enum.Value.html), and then to adapt my code accordingly.

Is this already possible?
If not, would this be unreasonably difficult? infefficient? any other reason for not doing it?

**Comment by timothee-haudebourg** [comment]
It seems like an overlook on my part. I have a family of `IntoJson` traits in the `json-syntax` crate, and it is implemented for `Object` but not for `ExpandedDocument`. I'll fix that.

Also there is an [`RdfQuads`](https://docs.rs/json-ld/latest/json_ld/trait.RdfQuads.html) trait that provides an iterator over the RDF quads. [It is implemented by `ExpandedDocument`](https://docs.rs/json-ld/latest/json_ld/struct.ExpandedDocument.html#impl-RdfQuads%3CT%2C%20B%2C%20M%3E-for-ExpandedDocument%3CT%2C%20B%2C%20M%3E) but it doesn't do everything the `toRdf` processor function does, that's why in is not provided by the `JsonLdProcessor` trait yet. See #46 for more details. Turns out I'm finishing implementing `toRdf` right now.

**Comment by pchampin** [comment]
> Turns out I'm finishing implementing toRdf right now.

Great!  My old implementation was incomplete, as it required an expanded form as input. I was hoping to plug your implem of `expand` to my implem of `toRdf`, but that will be even easier if you implement both! Please ping me when this is finished.

I guess I can then throw away the migration work that I have started to do, though :cry:

**Comment by timothee-haudebourg** [comment]
I released RDF deserialization with version 0.10.0 in #49.

**Comment by pchampin** [comment]
Closing this issue, as the implementation of `to_rdf` solved it for me.

**Comment by wont-work** [comment]
Hi, is there an update to this? Despite the issue being closed there *still* doesn't seem to be a way (or at least, and easily discoverable one) to convert ExpandedDocument to a json_syntax::Value.
